### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by vaiRk** [JulienBreux/jbx_menu#1]
Hi :),

I'm using the menu searching bar and friendly URL. It works fine but if you are in a product page and try to search something all you got is an error saying that search.php couldnt be found because its looking for it on www.yourstore.com/currentcategory. 

http://i51.tinypic.com/2ywzali.jpg

How can I fix this? thanks.

**Comment by JulienBreux** [comment]
Hi!

What is your PrestaShop version ? and menu version ?
(Sorry but your links are deads)

Best regards

**Comment by vaiRk** [comment]
My Prestashop version is 1.4.4.1 and I'm using the latest version of the menu.

Other searching modules worked fine.

**Comment by JulienBreux** [comment]
Can you give me an URL ?

Thx in advance.

**Comment by vaiRk** [comment]
No, the page it's not open to public yet. Sorry can be more usefull :_(

**Comment by JulienBreux** [comment]
Sorry but i don't help you if i don't reproduce issue.

I close this but when you've your store "online", i will help you!

Best regards and sorry yet :-/

**Comment by vaiRk** [comment]
Hi, 

I can give you a password to enter to my store in case you have a moment to check this issue. Thanks :)
