### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Saulouk** [JulienBreux/jbx_menu#2]
Hi,
I'm trying to use the menu module, I have it installed on PrestaShop™ 1.4.5.1 and when I try to configure it in the modules section the "Access denied" message comes up.

I have looked at a few things such as read and write rights to the file/folder and found no fix to it so I was hoping to see if you could give me a hand?

Thank you in advance!

**Comment by adijan** [comment]
Hello, 
I have the same problem...
help please...

THX
Jan

**Comment by Saulouk** [comment]
Oh so it isn't just me...

What host are you using?
I'm wondering if it's down to my server specs in a way, I've looked through the files and the php coding and to my basic knowledge it looks fine... really need it working or to find a replacement one.

Hope someone helps us out soon.

**Comment by uokis** [comment]
I had the same problem and the solution I found was:
1. I created a new profile (I set the name to "admin"), with all the rights.
2. I created a new employ with this profile,
3. I logged in with this new user and then, I can manage this module.

That's all.

**Comment by Saulouk** [comment]
uokis,
Thank you very much for the solution... cannot believe it was so simple and I did not think of it!
I just tried it out and can now get on with editing the theme, thank you once again!

**Comment by JulienBreux** [comment]
It's fixed in this latesst version.
I forget to initialize access, since 1.4, so sorry for all :)
