### ISSUE TITLE
Light value doesnt work

### ISSUE THREAD

**Issue by hbouzagl** [JulienBreux/jbx_menu#4]
Hello Julien,
I have see an issue with the light value not working. The package tested: menu 2.8.4 and prestashop 1.4.6.2
If you choose a color and a light value and then save it. The relod of the page and even the preview in admin doesnt take care about your choosed light value.

Thanks for your help sabving this point.
Regards
Henri

**Comment by bbonneton** [comment]
Hello Henri,

I had the same issue and made a small correction. You can take the changes from the pull request I've just created if you want.

Regards,
Bruno

**Comment by JulienBreux** [comment]
Thx :)

**Comment by hbouzagl** [comment]
Hello Bruno,
Thanks a LOT to share the solution, it works fine for me now!!
Regards
