### ISSUE TITLE
Cannot add links

### ISSUE THREAD

**Issue by theones** [JulienBreux/jbx_menu#8]
Cannot add links on prestashop 1.5.3.1. After add link i see in admin area blank page after header. 
![screen](https://f.cloud.github.com/assets/1378989/93059/fcf7f890-660a-11e2-9033-d2043398e40d.png)

**Comment by vmulot** [comment]
Same here, and in my php_error_log got : 

[08-Feb-2013 22:51:27] PHP Fatal error:  Uncaught exception 'PrestaShopException' with message 'Property Menu->title is not valid' in /path/to/my/local/site/classes/ObjectModel.php:837
Stack trace:
#0 /path/to/my/local/site/modules/jbx_menu/menu.class.php(25): ObjectModelCore->validateFields()
#1 /path/to/my/local/site/classes/ObjectModel.php(464): Menu->getFields()
#2 /path/to/my/local/site/modules/jbx_menu/menu.class.php(60): ObjectModelCore->add(true, true)
#3 /path/to/my/local/site/classes/ObjectModel.php(426): Menu->add(true, true)
#4 /path/to/my/local/site/modules/jbx_menu/menu.class.php(54): ObjectModelCore->save(true, true)
#5 /path/to/my/local/site/modules/jbx_menu/AdminModuleMenu.php(153): Menu->save()
#6 /path/to/my/local/site/fun in /path/to/my/local/site/classes/ObjectModel.php on line 837

**Comment by vmulot** [comment]
In AdminModuleMenu.php, i changed ligne 489 : 
<input type="text" name="title['.$language['id_lang'].']"
by 
<input type="text" name="title_'.$language['id_lang'].'"

It seems to work

**Comment by JulienBreux** [comment]
Thx for your feedback.

**Comment by dpcdpc11** [comment]
Thanks vmulot for the solution... but there's another problem with the Title of the Menu Items.
No mater what I do, the title is not saved... do any of you experience this problem?

**Comment by vmulot** [comment]
Yeah i have the same pb, didn't have the time to try to fix that yet :)
for the moment i'm updating field using phpmyadmin in order to have the title.

**Comment by dpcdpc11** [comment]
I did the same... I'm really close on the dead line and I have to finish some more important stuff... I spent a couple of hours fiddling with the code but couldn't find a solution.
Hopefully a solution is on it's way!

**Comment by armand1984** [comment]
Hi, first of all, do not change line 489 as stated before, leave it as it is.
Then, remove "title" field validation from menu.class.php

Lines 21 and 22 should look like this:
protected $fieldsSizeLang = array('link' => 128);
protected $fieldsValidateLang = array('link' => 'isCleanHtml');

**Comment by dpcdpc11** [comment]
@armand1984 this partially does the trick... thank you for your involvement, but... there's a but!
When editing a Menu Item, the Title field becomes blank once again. Can anyone confirm this?
